# Generated by Django 3.2.4 on 2021-06-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250)),
                ('preco', models.FloatField()),
                ('foto', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Produtos',
            },
        ),
    ]
